### ISSUE TITLE
图标缺失、功能跟进

### ISSUE THREAD

**Issue by i2qaq** [ljxi/Cloudflare-R2-oss#1]
![image](https://github.com/ljxi/Cloudflare-R2-oss/assets/104718844/4ec2623f-556e-4084-8895-f4072b1cb3b3)
![image](https://github.com/ljxi/Cloudflare-R2-oss/assets/104718844/adb0be0c-9f5a-4296-a13a-677a2756ebe5)
![image](https://github.com/ljxi/Cloudflare-R2-oss/assets/104718844/3908600e-28d0-4f09-a346-01e455df18df)

作者大大，图里的这些资源都失效了，是否可以更新一下替代图标呢？

另外，上游仓库的这个 [commit](https://github.com/longern/FlareDrive/commit/f82ffdcf5d8475ee455341faca388c62c2319f9d) 新增了 copy&paste 功能，是否也可以一并跟进一下呢？

盼作者大大能拨冗更新，谢谢😊！

**Comment by ljxi** [comment]
copy&paste功能已经跟进了，不过图标缺失问题我这里没有遇到，可能是因为cf的连接不稳定

**Comment by i2qaq** [comment]
经您提醒才发现，图标缺失是我的问题，魔法访问 [图标](https://cdnjs.cloudflare.com/ajax/libs/material-design-icons/4.0.0/png/file/folder/materialicons/36dp/2x/baseline_folder_black_36dp.png) 就会404，应该是魔法的 ip 被 ban 了😂。

总之谢谢作者大大的更新和回复，问题解决了😘
